### ISSUE TITLE
Scrolling isn't intuitive enough

### ISSUE THREAD

**Issue by WillNilges** [nycmeshnet/meshforms#35]
There has been some confusion with the new query form and the fact that it scrolls. We need to work on the issues of width/screen real estate, and ensure that all fields can be viewed on one screen.

**Comment by WillNilges** [comment]
Fixed with legacy mode, but the "new" grid layout should also get some more TLC

**Comment by andybaumgar** [comment]
I think we could handle this by just showing the scroll bar in the table.  Currently it appears to be hidden / not showing.

**Comment by WillNilges** [comment]
I'm tired of looking at this issue.
