### ISSUE TITLE
Un-hardcode grandsvc

### ISSUE THREAD

**Issue by james-otten** [nycmeshnet/meshforms#68]
grandsvc is hardcoded into the image, which causes forms to not point to non-grandsvc meshdb instances.

From inside the container on dev3:
```
/app $ grep grandsvc -R . | wc -l
9
```
Steps to reproduce:
1. Fill out the join form
2. Notice the CORS error

**Comment by james-otten** [comment]
https://github.com/nycmeshnet/meshforms/blob/main/.github/workflows/publish-and-deploy.yaml#L39

Setting the secret `MESHDB_URL` to `https://db.mesh.nycmesh.net` will be the one off to avoid dealing with environments.

**Comment by WillNilges** [comment]
oh right I remembered that this was an issue this weekend. Ughhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh

**Comment by WillNilges** [comment]
> https://github.com/nycmeshnet/meshforms/blob/main/.github/workflows/publish-and-deploy.yaml#L39
> 
> Setting the secret `MESHDB_URL` to `https://db.mesh.nycmesh.net` will be the one off to avoid dealing with environments.

I don't think we can safely connect the dev meshforms to prod. Is that your intention?
